### ISSUE TITLE
Replace laxar-uikit/controls/i18n with laxar-i18n-control

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/ax-headline-widget#14]
As mentioned in LaxarJS/laxar-uikit#135, uikit controls have been extracted to their own repos.
/cc @x1B @alex3683 @jonaswjs

**Comment by jpommerening** [comment]
(Not sure about the "breaking" label. This might be non-breaking, if the control can be used as is and dependency resolution works properly …)

**Comment by x1B** [comment]
Marking as _enhancement_ since this is about LaxarJS v2 compatibility. For LaxarJS v1, the old control should work just fine.

**Comment by x1B** [comment]
This currently prevents the v4.0.0-alpha.0 from working properly.
For now, I'll solve this by removing pre-computing localizations (the widget does this for almost all localizations anyway).

**Comment by x1B** [comment]
Fixed on `master` (`v4.0.0`).
